### ISSUE TITLE
Provider abstraction and extension 

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#9]
Extending from the FABRIC + Chameleon work, we want to beef up the Provider and Model base to support many providers.

We can use SENSE and GENI as the pilots for this abstraction and extension to achieve better generality as well as to develop the best practices for adding other providers. 

`ETC: by end of Q4 2022` 

We should firstly support SENSE by end of November so that we can have initial capability for FABRIC / AL2S_CloudConnect  + SENSE_AWS workflow by I2 TechExchange time (Dec 5-9).

**Comment by disprosium8** [comment]
GENI is not an issue in my mind - the slice/node/network abstraction we have works just fine.  SENSE I am not sure.  For services, there two things we need to address in my mind:

1. Resources with different providers associated with same slice (I began by adding resource provider override in https://github.com/fabric-testbed/fabfed/tree/ek-services).  Will need discussion.
2. Sharing resource information between providers under same slice. For example, services will need to extract credentials for provisioned nodes so that they can perform setup tasks. Additionally, we want to extend the provider model so that we can export all credentials for user-driven Ansible workflows.
