### ISSUE TITLE
Add and test Jupyter notebooks for fabfed example workflows

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#97]
We need a design that uses the Jupyter notebooks as an interface to present the fabfed to users. 

* [x] 1. Install the fabfed package and add the needed configs through the JupyterHub terminal CLI. A single install script is preferred, but we can start with some manual steps.
* [x] 2. Create a set of notebooks that demo the examples provided in the [FabFed Users Manual](https://learn.fabric-testbed.net/knowledge-base/fabric-federation-extension-fabfed-users-manual/). They should cover all the providers and roughly the same demos we provided at KNIT-7. 
* [x] 3. Test through all the notebooks. 
* [x] 4. Create notebooks that use FabFed python function/methods to repeat the above task.

**Comment by zlion** [comment]
- Set up the initial structure of Jupiter notebook scripts.
- Installed the latest version of fabfed-py (1.7.0b) within notebook

**Comment by zlion** [comment]
-  Created Jupyter notebooks for all providers: fabric, aws, gcp, sense-aws, sense-gcp, cloudlab and Chameleon. 
-  Tested workflows for all stitching cases described in the manual
-  Reported the issues in GitHub

Now working on notebooks using FabFed python functions to create workflow.

**Comment by abessiari** [comment]
@zlion 
For the two quick scenarios we have discussed we should probably have a getting started section which would allow people to run  the network stitching in less than two minutes ...

**Comment by abessiari** [comment]
@zlion
The description for plan should something like this. It does a whole lot more than list the resources: 
I recommend: 
Creates an execution plan which lets you preview the changes before applying








[8:30](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473454561099)
fabfed_manager.show(session=session_name)
[8:31](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473492040409)
This shows the states of was deployed .... It is important. It should be by itself after the apply and after the destroy
[8:31](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473507373399)
Provider states ....
[8:32](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473534843989)
if destroy is successful it would show an empty list
[8:34](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473679499539)
add two cells after destroy one for show (state) and the other for session.
[8:36](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710473766721819)
Tell me you are not planning on having tons of notebooks. One suffices. It is Ramadane. So I pray ...
:pray:
[8:40](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710474022961899)
Just add the cloudlab installtion to the rest. The only reason 
[@Ezra Kissel](https://fabric-testbed.slack.com/team/UV5U2AJ8M)
 separated it is because there were some issues when pushing it to pypi.
[8:41](https://fabric-testbed.slack.com/archives/C03PFJGHHEV/p1710474060646369)
so after installing fabfed install cloudlab ...

**Comment by abessiari** [comment]
show is pretty important it displays the state .... it should have its own cell

```
fabfed_manager.show(session=session_name)
```

**Comment by abessiari** [comment]
show (state) and show sessions should be after apply and after destroy. 

after destroy if all is well they will both display an emty list

**Comment by abessiari** [comment]
Listing resources is a few lines. We should have it in its own cell after validate. 

The code here lists the resources in the order they will handled. 

```
for resource_config in config.resource_configs:
            dependencies = []

            for dependency in resource_config.dependencies:
                dependencies.append(dependency.resource)

            print(resource_config.label, "depends on ", dependencies)
```

**Comment by abessiari** [comment]
For chameleon no need for two files. Add a variable site that defaults to STAR.
The only difference is the site. One has STAR and the other has TACC.  So basically one config under chameleon suffices. You can then go with the default STAR or if you want TACC you use variables. (edited)
